name: 'Pick commit'
description: 'Pick last successful commit from a repo'
inputs:
  repo:
    description: 'Github repository e.g. llvm/llvm-project'
    required: true
  token:
    description: 'Github auth token'
    required: true
outputs:
  sha:
    description: 'The SHA1 of the picked commit'
runs:
  using: 'node12'
  main: 'index.js'
